### ISSUE TITLE
Grey opaque window

### ISSUE THREAD

**Issue by jeremychevallier** [justinfrankel/licecap#100]
As you see here, LICEcap seems not to be able to see anything:

![Screen Shot 2021-02-04 at 10 01 35 AM](https://user-images.githubusercontent.com/16313585/106928009-f7684000-66cf-11eb-9fe2-7fe1dbfc5905.png)

resulting in this GIF:

![notion groceries uncheck all](https://user-images.githubusercontent.com/16313585/106928108-14047800-66d0-11eb-8ed6-ec97bb83f360.gif)

but it has screen recording permissions in Big Sur:

<img width="780" alt="Screen Shot 2021-02-04 at 10 02 40 AM" src="https://user-images.githubusercontent.com/16313585/106928150-1ebf0d00-66d0-11eb-9992-03f089a971b0.png">

Am I missing something? Going to try a restart later & report back.

**Comment by matt** [comment]
Yes, you're missing https://github.com/justinfrankel/licecap/issues/92, https://github.com/justinfrankel/licecap/issues/97, and https://github.com/justinfrankel/licecap/issues/98.

See https://github.com/justinfrankel/licecap/issues/92#issuecomment-773028638 for an Intel based solution and please close this duplicate issue.

**Comment by jeremychevallier** [comment]
Awesome, thank you Matt. Will dive into the other issues. Appreciate your fast respose.
