### ISSUE TITLE
Blank screen with moving mouse on macOS Ventura

### ISSUE THREAD

**Issue by AshishKapoor** [justinfrankel/licecap#119]
A recorded Gif file is giving a blank screen with a moving mouse on macOS Ventura

**Screenshot**
<img width="541" alt="Screenshot 2022-11-17 at 12 08 14 PM" src="https://user-images.githubusercontent.com/5203107/202374384-b319e86b-dc22-427f-b5d4-fac0f788d03e.png">

**Comment by FrankWang117** [comment]
Try this version:

LICEcap v1.31 for macOS (Feb 17 2021) (876kb DMG)

https://www.cockos.com/licecap/licecap131.dmg

**Comment by PYUDNG** [comment]
> Try this version:
> 
> LICEcap v1.31 for macOS (Feb 17 2021) (876kb DMG)
> 
> https://www.cockos.com/licecap/licecap131.dmg

Yes, this works (on my MacOS Catalina).

**Comment by AshishKapoor** [comment]
Works!
