### ISSUE TITLE
What in LiceCap hotkeys for «Record...» and «Stop»?

### ISSUE THREAD

**Issue by Kristinita** [justinfrankel/licecap#18]
[Here](https://dottech.org/127281/windows-review-licecap-mac-os-x/) they write that they do not exist. Whether so it?

My OS — Windows 10.

**Comment by selesnow** [comment]
Hi.
Ctrl + Alt + P 
For pause and Rec if you chose this option before record.

![](http://img.netpeak.ua/alsey/151378613437_kiss_5kb.png)

**Comment by Kristinita** [comment]
@selesnow , thanks, it works for Licecap 1.28!

**Comment by falsefalse** [comment]
Couldn't make it work on OS X, apparently Alt ≠ Option 😿

**Comment by esaruoho** [comment]
@falsefalse same situation here, even after ticking the Control+Alt+P pauses recording tickbox, nothing happens when attempting to press Control-option-P

**Comment by shivam-rallyhealth** [comment]
Any updates?
