### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MD-78** [justinfrankel/licecap#22]
Just got this crash when recording to 25fps LCF file:

Name der fehlerhaften Anwendung: licecap.exe, Version: 0.0.0.0, Zeitstempel: 0x56813fdc
Name des fehlerhaften Moduls: licecap.exe, Version: 0.0.0.0, Zeitstempel: 0x56813fdc
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0003e078
ID des fehlerhaften Prozesses: 0x8d0
Startzeit der fehlerhaften Anwendung: 0x01d20e782c96d97b
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\LICEcap\licecap.exe
Pfad des fehlerhaften Moduls: C:\Program Files (x86)\LICEcap\licecap.exe
Berichtskennung: 705cab4b-7a6b-11e6-8a98-0019d1262458

LiceCap 1.26 (Windows 8.1 x64)

**Comment by MD-78** [comment]
This seems to be happening on mouse clicking links in websites (that I'm capturing).

**Comment by MD-78** [comment]
I have the LCF file I'm recording to (same file name) opened in REAPER the same time (as item in arrangement). That's what's causing the crash. Doesn't happen with GIF files tho.

**Comment by MD-78** [comment]
FIXED (1.27)

**Comment by esaruoho** [comment]
@MD-78 where were you able to download a Licecap 1.27?

**Comment by MD-78** [comment]
https://forum.cockos.com/showthread.php?t=156366

**Comment by esaruoho** [comment]
What's a "landoleet"?

**Comment by MD-78** [comment]
https://forum.cockos.com/showthread.php?t=22836

**Comment by esaruoho** [comment]
@MD-78 thanks for the links, but i am not entirely sure why you're linking me to Reaper when I'm actually using LiceCap. Are these done by the same company or somesuch thing? Is 1.27 only for Windows or also for OSX?

**Comment by esaruoho** [comment]
Newest build is at https://www.landoleet.org at licecap127.dmg
