### ISSUE TITLE
OSX: Sierra/High Sierra/Mojave: Licecap captures black screen if two monitors connected EXTERNAL MONITOR ERROR

### ISSUE THREAD

**Issue by esaruoho** [justinfrankel/licecap#31]
If I'm on monitor#2 on macOS Sierra/High Sierra - licecap captures a black screen on monitor#2.
if I have monitor#2 connected, monitor#1 records black screen. i have to yank out monitor#2 to be able to get a non-blackscreen version from LiceCap. 
Detail: I do see my cursor moving in the animated gif, but everything else is black :)

**Comment by BMorearty** [comment]
I too am seeing a black recording with only a cursor on High Sierra--but I see it even _after_ yanking out my second monitor.

**Comment by esaruoho** [comment]
@bmorearty did you restart licecap after yanking out monitor?

**Comment by BMorearty** [comment]
@esaruoho Oops, no I didn't. After restarting it worked. In fact after restarting it worked even with my second monitor attached. (Recording on the first monitor.)

**Comment by esaruoho** [comment]
can verify this still happens with 1.27.

**Comment by justinfrankel** [comment]
Hmm using 1.28 with a RMBP and thunderbolt display, everything is fine -- can you go to "about this mac", "System report", and post a copy of your system report? or email it to me (support at cockos dot com)?

**Comment by esaruoho** [comment]
@justinfrankel I will when I'm at the office tomorrow! I use a rig where I have one Thunderbolt display and one HDMI display - and will write a few steps to replicate and send the details.

**Comment by esaruoho** [comment]
@justinfrankel  Oh, I've sent a system report your way now :)

**Comment by justtonytone** [comment]
@justinfrankel i am having the same issue, let me know if you need anymore system reports to help debug the issue.

**Comment by asoorm** [comment]
![caching](https://user-images.githubusercontent.com/1465130/35728150-8864f1f0-0802-11e8-9e43-ec31b2d4ba30.gif)

**Comment by esaruoho** [comment]
@justinfrankel how can we help with this, please? :) it's pretty much the only bug I've been having with this app, since starting to use it in May 2017.

**Comment by justinfrankel** [comment]
Maybe someone with this issue can debug it a bit? I can't duplicate on any of my macs.

**Comment by justinfrankel** [comment]
Actually, try this: https://landoleet.org/licecap128clang.dmg

**Comment by esaruoho** [comment]
I'll try this on Monday! thanks :)

**Comment by esaruoho** [comment]
@justinfrankel i ran this on a setup with 2 external monitors, using licecap128clang.dmg.

unfortunately, this was the result (i recorded using 2nd monitor)
![hoexicjasdf](https://user-images.githubusercontent.com/4966687/35848175-c43299aa-0b25-11e8-9125-1283421ac009.gif)

**Comment by ucg8j** [comment]
Licecap is a great piece of software, and this is the only issue I have encountered having used it for a year.

My specs are consistent with @asoorm 
macOS High Sierra
Macbook Pro 13" 2017
Intel Iris Plus Graphics

Additionally, I have replacated this issue with a 24inch and a 27inch external monitor.
My current fix is: Unplug monitor, restart machine, take LiceCap screencapture, plug second monitor in.
I tried OSS alternatives, but none are as good as Licecap.

**Comment by nicwinn** [comment]
Sometimes happens to me as well. Using monitors on HDMI or Thunderbolt.
<img src="https://user-images.githubusercontent.com/9751044/36854206-04888e3e-1d36-11e8-9bb8-2d9fdc6e3f64.png" alt="specs" width="275" />
LICEcap: Version 1.28

**My fix:**
1. unplug the external monitor
2. start LICEcap
3. test
4. plugin the monitor
5. run LICEcap on the external monitor

My guess is a memory issue. Somehow this forces it to clear out and start over.

**Comment by JulieMarie** [comment]
Glad I found this today.  LICEcap had been working just fine on my external monitor(s) until I tried to use it today and got the black screen.  When I saw @nicwinn comment about memory, I actually restarted my Mac before going through the rest of the steps and I'm back to LICEcap working.

**Comment by jillesme** [comment]
Yep it happens *sporadically* for me as well 😞 . I have "Giphy Capture" as back-up but it's nowhere near as good as LICEcap.

**Comment by joemidi** [comment]
Thanks for this! I can't install things on the work laptop, so trying to find another bit of software for a quick Gif was have taken ages!

**Comment by aarcro** [comment]
![screenshot 2018-07-20 23 37 10](https://user-images.githubusercontent.com/279725/43031747-e2f2b9ca-8c75-11e8-85aa-0c4502a2957c.png)

LICEcap 1.28

First day with the tool. Worked fine with my normal HDMI second monitor through caldigit USB-C dock. Switched to AOC USB-C travel monitor and now recording black, even after restarting LICEcap.

**Comment by ganjarpanji** [comment]
also experiencing this issue 😢 1.28

**Comment by frumbert** [comment]
Can Confirm MBP 2016 has same issue (same specs as @aarcro) and only occurs once the external 4k monitor is connected via HDMI. Recording from either monitor records only black; unplug + relaunch app then records from internal screen ok. Not the end of the world, but slightly annoying

**Comment by nicwinn** [comment]
Y'all this has to be some sort of memory issue. I'll go out on a limb and say we `power users` have a lot of hidden processes running in the background. Google Chrome is a big offender on my list which just so happens to be where I am usually capturing something in Licecap. With all that said, my next step after a reboot would be a [Safe Boot into Safe Mode](https://support.apple.com/kb/ph25617?locale=en_US). (be sure to wait on the bong sound or it will disable Bluetooth and you will lose your keyboard, if you are using one) This startup process will do a few things, one of which(flushing a lot of system cache files) may permanently fix the issue. I haven't tried it myself so Licecap may not run at all in Safe Mode if too many resources are toggled off. But the Safe Boot process itself may clear something out of the way for when you go back to it in a normal reboot.

**Comment by esaruoho** [comment]
@nicwinn I appreciate the suggestion, however, no app should require `Safe Boot in Safe Mode` to start functioning with multiple monitors. Also, Google Chrome is just "an area of the screen" to LiceCap - I have never had issues recording areas of the screen that include Google Chrome, Opera, Safari, Firefox, MSEdge, Ableton Live, Unity Editor, Renoise, Virtual machines etc, with LiceCap.

**Comment by frumbert** [comment]
I tried the safe mode boot to clear caches.

Interestingly if I plug in an external monitor (1440) using a mini display port to dual-link dvi adaptor then start licecap on the external monitor and record, i do not get the black background in the recording. If however I then move licecap to my mbp monitor and record, the black appears. The black then stays regardless of which monitor I connect it to. When connecting a 4k to the hdmi port, i always get the black box regardless of which monitor I start on.

so it's got something to do with graphics switching or graphics memory when it changes.

**Comment by nicwinn** [comment]
@esaruoho First, I didn't mean to suggest that it was because I was trying to capture the Chrome window specifically, just that I have it open because it is my goto browser and it is a resource hog. That in combination with 1) a host of other applications in the foreground and 2) all the various "system extras" I have running in the background. Second, I didn't mean to suggest always going into safe mode to run a capture. Just that since I believe memory might have something to do with it and the safe boot process supposedly dumps some system caches, then a one-time maintenance reboot might be worth a shot for some folks. If it does work well in safe mode only then it may be possible that some third-party configuration is fouling up the process.

**Comment by ganjarpanji** [comment]
@nicwinn IMO if this work, this could be just a workaround though, proper fix in the app side will be much better :)

**Comment by frumbert** [comment]
Reduce motion isn't needed for me; reduce transparency seems to be the workaround.

**Comment by nicwinn** [comment]
> @nicwinn IMO if this work, this could be just a workaround though, proper fix in the app side will be much better :)

Agreed. Just brainstorming. Note: I have made several gifs since my last post and had zero issues.

**Comment by Conorbro** [comment]
Unplugging all external monitors and restarting LICEcap resolved the black screen recordings for me on my MBP with the following specs: 

<img width="328" alt="screen shot 2018-09-19 at 12 19 26" src="https://user-images.githubusercontent.com/5826063/45750275-4a77f000-bc06-11e8-8d34-3ed2b05a68b4.png">

**Comment by dialex** [comment]
Same issue and I'm not connected to any external monitor
![image](https://user-images.githubusercontent.com/2140450/47650732-1387e900-db79-11e8-9e9d-25844b03a2ee.png)

**Comment by reaperblog** [comment]
Frankel pls
MacBook Pro 15" 2015, Dell monitor connected through thunderbolt hub HDMI.

**Comment by ladjzero** [comment]
Same issue. Mac 10.13.6 (17G65) licecap Version 1.28

**Comment by Shawock** [comment]
I'm using MacBook Pro (Retina, 13-inch, Early 2015) 10.13.3, unplug external monitor, reopen Licecap then records from built-in screen. 
![test8](https://user-images.githubusercontent.com/10074938/51400893-78ede380-1b84-11e9-9ac7-feb8c5a1923c.gif)

**Comment by dialex** [comment]
But did you try to switch to another virtual desktop, using the `Ctrl+Left/Right arrow` or the three fingers gesture? That's what causes the "motion blur" in my recording.

**Comment by IAfanasovMob** [comment]
Have the same issue. restart of mac and accessibility settings adjustments doesn't help 

![Screen Shot 2019-03-14 at 16 54 19](https://user-images.githubusercontent.com/44999963/54371538-d466ba00-4679-11e9-9ddd-3c860aee0372.png)

**Comment by arjunlol** [comment]
Having the same issue, tried disconnecting monitor and restarting 😕 

![reassign](https://user-images.githubusercontent.com/22333438/54543703-8650ff80-4974-11e9-86ea-ac8044b61b90.gif)

![image](https://user-images.githubusercontent.com/22333438/54543660-6faaa880-4974-11e9-84da-1da5c86a868b.png)

**Comment by voronianski** [comment]
the same issue here :(

**Comment by wolasss** [comment]
I have the same issue: Macbook Pro: 
<img width="323" alt="Screenshot 2019-04-25 at 12 58 28" src="https://user-images.githubusercontent.com/1525324/56731061-daac8380-6759-11e9-845f-2e5c8e119314.png"> and Licecap 1.29

**Comment by dialex** [comment]
> _Hello @justinfrankel, my old friend,_
> _I've come to talk with you again._
> _Because an issue softly creeping_
> _Left its bug while I was updating_
> _And the issue that was planted in my mac_
> _Still remains_
> _Within the sound of silence_

😢

**Comment by gvilarino** [comment]
Same issue here:

![image](https://user-images.githubusercontent.com/2538465/60736297-d73d3180-9f2c-11e9-9dc4-dbddd6e638d2.png)

**Comment by gmarinov** [comment]
still happening? Mojave.

**Comment by esaruoho** [comment]
@gmarinov this seems to be a stupendously well-neglected issue and looks like there are no fixes forthcoming to this - unless if someone figures out how to fix it as a 3rd party and send in a PR.

**Comment by luis-admios** [comment]
Go to system preferences > Privacy & Security > Privacy > Add LICECap to the 'Allow the apps below to control your computer' list and enjoy. yw!

**Comment by gmarinov** [comment]
@luis-admios no

![gif](https://user-images.githubusercontent.com/14101296/62610374-7cb43e00-b8fb-11e9-916b-7a0c342240fa.gif)

**Comment by luis-admios** [comment]
@gmarinov it worked for me.

**Comment by woodyhayday** [comment]
As @luis-admios said, adding to privacy & security seems to have fixed for me:

<img width="670" alt="Screenshot 2020-02-27 at 07 35 33" src="https://user-images.githubusercontent.com/6525765/75422150-d5006b00-5933-11ea-91fb-c7d98cb99e43.png">

Perhaps all this bug needs is a prompt to load that mac setting if somehow accidentally dismissed without checking the box.

**Comment by dialex** [comment]
hmmm I don't even have that option... what is you macOS version? I have 10.14.6

![Screenshot 2020-02-27 at 10 34 26](https://user-images.githubusercontent.com/2140450/75436631-d0947c00-594c-11ea-93a8-b2623dc7f1f2.png)

**Comment by woodyhayday** [comment]
Is it under Accessibility?

<img width="584" alt="Screenshot 2020-02-27 at 14 00 15" src="https://user-images.githubusercontent.com/6525765/75452090-8968b400-5969-11ea-9dd8-39259532e4a6.png">

**Comment by dialex** [comment]
No :(
Neither of the left side options show Licecap on the right side. I tried installing Licecap manually and through brew.

**Comment by Meyer-Hallot** [comment]
> As @luis-admios said, adding to privacy & security seems to have fixed for me:
> 
> <img alt="Screenshot 2020-02-27 at 07 35 33" width="670" src="https://user-images.githubusercontent.com/6525765/75422150-d5006b00-5933-11ea-91fb-c7d98cb99e43.png">
> 
> Perhaps all this bug needs is a prompt to load that mac setting if somehow accidentally dismissed without checking the box.

It seems that Catalina removed the option to manually give an app permission to record your screen. It seems the only time you can give an app that permission now is when it prompts you for it. Since licecap doesn't prompt you cant give it permission under normal circumstances. 

I did manage to find a work around though. For some reason manually adding licecap to the Developer Tools list allows it to bring up the screen recording permissions prompt when you start recording.

![Screen Shot 2020-04-21 at 10 12 25 AM](https://user-images.githubusercontent.com/16855412/79876230-c7f27c00-83b8-11ea-9a4c-5087975c1f15.png)
![Screen Shot 2020-04-21 at 10 12 35 AM](https://user-images.githubusercontent.com/16855412/79876236-c88b1280-83b8-11ea-81a8-562b842b3862.png)

**Comment by dialex** [comment]
Thank you @Meyer-Hallot :)
I'm using Mojave and I don't that "Developer Tools" option. I manually added Licecap to the "Accessibility" option, but it didn't solve the issue 🤷‍♂️I already accepted this will never work again

**Comment by ninamarina** [comment]
This is still happening on Catalina.

**Comment by cwalworth** [comment]
@ninamarina 

I figured out how to get it working for me on both screens, but it's not the most ideal solution. 

<img width="665" alt="Screen Shot 2020-06-12 at 13 05 44" src="https://user-images.githubusercontent.com/19628475/84542348-239cff80-acae-11ea-8e3e-7c32140820cf.png">

1. Close licecap
1. Make external display your primary
1. Start licecap
1. You should be able to record on both screens now

Changing my primary display back breaks it for me. I've tried several different combinations but the above is the only one that seemed to work for me.

I'm also only using one external monitor, so I can't confirm that this method will work on other setups.

_* I used all the suggestions from the previous comments too_

**Comment by ninamarina** [comment]
@cwalworth thanks! I'll try that :)

**Comment by NigelThorne** [comment]
I get blank screens unless I start LICEcap from the terminal as sudo.

**Comment by qianjin1017** [comment]
Ugh, I also met the same problem. Now I am very upset about what causes it? If the solution is expected to inform.
![34234](https://user-images.githubusercontent.com/19699178/88266585-070ad300-cd02-11ea-8f3f-a9425cdc469c.gif)

**Comment by stgarf** [comment]
I'm hesitant and sad to even suggest this since licecap generated smaller and higher quality gifs (imo) and has been such an excellent go-to for such a long time and I'm sure we'll eventually see some action here but in the meantime there's [kap](https://github.com/wulkano/Kap/blob/master/README.md) for macOS which works fine enough.

**Comment by esaruoho** [comment]
closing issue. probably still happens. just bored of being notified about it for years on end. it's been 3 years.

**Comment by sanchezg** [comment]
Still happening for me.

![image](https://user-images.githubusercontent.com/6667980/93685776-1d29db00-fa88-11ea-8631-44857fb65917.png)
![image](https://user-images.githubusercontent.com/6667980/93685808-40548a80-fa88-11ea-88e4-fd692c357351.png)

**Comment by chriswoolfe** [comment]
Adding it here fixed it for me. 
![image](https://user-images.githubusercontent.com/5896087/95383132-b34b6700-08b8-11eb-8646-fdcc68c79da9.png)

**Comment by beders** [comment]
Can confirm. That works. Thank you!

**Comment by KarlBaumann** [comment]
Broken. None of the fixes mentioned here work. 
Are there any alternatives to this app?

**Comment by anderoonies** [comment]
Sorry to the issue creator for another notification, but on Big Sur it appears this is now controlled by the Screen Recording setting in Security & Privacy

**Comment by joelPR** [comment]
For me worked doing these three things:
- Make the external monitor the primary one
- Mark Elapsed time in LiceCap
- Mark Use .GIF transparency for smaller files in LiceCap

**Comment by ralstonroman** [comment]
> As @luis-admios said, adding to privacy & security seems to have fixed for me:
> 
> <img alt="Screenshot 2020-02-27 at 07 35 33" width="670" src="https://user-images.githubusercontent.com/6525765/75422150-d5006b00-5933-11ea-91fb-c7d98cb99e43.png">
> 
> Perhaps all this bug needs is a prompt to load that mac setting if somehow accidentally dismissed without checking the box.

Works for me, Thanks 👍

**Comment by sarink** [comment]
Licecap was already in my screen recording privacy settings... however, after removing it and re-adding it, the problem is fixed.

**Comment by silva96** [comment]
> @ninamarina
> 
> I figured out how to get it working for me on both screens, but it's not the most ideal solution.
> 
> <img alt="Screen Shot 2020-06-12 at 13 05 44" width="665" src="https://user-images.githubusercontent.com/19628475/84542348-239cff80-acae-11ea-8e3e-7c32140820cf.png">
> 
> 1. Close licecap
> 2. Make external display your primary
> 3. Start licecap
> 4. You should be able to record on both screens now
> 
> Changing my primary display back breaks it for me. I've tried several different combinations but the above is the only one that seemed to work for me.
> 
> I'm also only using one external monitor, so I can't confirm that this method will work on other setups.
> 
> _* I used all the suggestions from the previous comments too_

this worked for me

**Comment by vinhthuy2** [comment]
I can confirm it's still an issue today.
Toggling the `Privacy & Security` also works.


> > As [@luis-admios](https://github.com/luis-admios) said, adding to privacy & security seems to have fixed for me:
> > <img alt="Screenshot 2020-02-27 at 07 35 33" width="670" src="https://user-images.githubusercontent.com/6525765/75422150-d5006b00-5933-11ea-91fb-c7d98cb99e43.png">
> > Perhaps all this bug needs is a prompt to load that mac setting if somehow accidentally dismissed without checking the box.
> 
> Works for me, Thanks 👍
