### ISSUE TITLE
1.27 OSX black isn't black - images filtered all wrong

### ISSUE THREAD

**Issue by esaruoho** [justinfrankel/licecap#33]
hi i just took 1.27 from http://landoleet.org and gave it a try.
going back to 1.25 since stuff looks like this when recorded on macOS High Sierra.

![black recordings23](https://user-images.githubusercontent.com/4966687/33482302-047f811c-d6a1-11e7-9d14-c59bb4e0a9f4.gif)

**Comment by justinfrankel** [comment]
Thanks, fixed in git, will post release soon.

**Comment by justinfrankel** [comment]
1.28 posted to landoleet, with a new icon too!
