### ISSUE TITLE
Unable to compile with Xcode on macOS High Sierra

### ISSUE THREAD

**Issue by esaruoho** [justinfrankel/licecap#34]
Hi @justinfrankel, I'm attempting to compile this using Xcode 9.1 - and the first thing it tells me is that 10.4 is no longer supported, I switch to 10.6 just to make sure, then I start getting oodles and oodles of errors:
<img width="792" alt="screen shot 2017-12-02 at 14 55 15" src="https://user-images.githubusercontent.com/4966687/33515837-d39d5a6c-d770-11e7-9a83-ab83585bf99e.png">

how do I solve this? I'm just looking to look through the Pull Requests so can get a newer icon and see what other things have been fixed, but so far no luck.

**Comment by justinfrankel** [comment]
Should be fixed in git now (there are a few things wrong not worth explaining) -- you'll need to change the project to use the latest macOS SDK and minimum deployment target to 10.6, but it should compile.

**Comment by esaruoho** [comment]
Thanks @justinfrankel ! I was able to compile and run it locally :)
