### ISSUE TITLE
Provide releases/tags in this repo

### ISSUE THREAD

**Issue by dialex** [justinfrankel/licecap#35]
The official website lists 1.25 as the latest version for Mac, however the latest commit mentions version 1.28. Can you use GitHub's Releases to provide the latest binaries to the community?

**Comment by esaruoho** [comment]
@dialex https://www.cockos.com/licecap/ nowadays gives a 1.28 version for windows and osx. does that help? :)

**Comment by dialex** [comment]
a-ha! It has been updated in the meantime, thanks
