### ISSUE TITLE
Licecap may affect the performance of your Mac - need 64-bit compatible version of Licecap

### ISSUE THREAD

**Issue by esaruoho** [justinfrankel/licecap#40]
Hi, I'm running macOS High Sierra Beta which now warns about 32-bit apps (suggesting I should always be running 64-bit apps)

and got this when booting up LICEcap:
<img width="446" alt="screen shot 2018-01-26 at 14 30 58" src="https://user-images.githubusercontent.com/4966687/35439909-a34b4076-02a5-11e8-9601-c6d5b2b2c98e.png">

**Comment by justinfrankel** [comment]
We'll make future versions 64-bit universal (for now try https://landoleet.org/licecap128clang.dmg )

**Comment by esaruoho** [comment]
Thanks @justinfrankel ! :)

**Comment by natebeaty** [comment]
Thanks for this, I was just getting crashes on the currently listed download on latest OS X when I tried to hit `Record...` button. This version works!

**Comment by saimonmoore** [comment]
Hi,
Running into this since I upgraded to OSX High Sierra 10.13.6 but the link to the dmg above is broken :(

**Comment by esaruoho** [comment]
seems like there is a PR at #49 which is waiting for @justinfrankel to merge it in.

**Comment by esaruoho** [comment]
@justinfrankel hmm.. so, will there be a 64-bit version that is better than the #49 PR?

**Comment by esaruoho** [comment]
closing since it works on macOS Monterey and Big Sur.
