### ISSUE TITLE
64-bit version for macOS is also needed

### ISSUE THREAD

**Issue by valentin-nasta** [justinfrankel/licecap#46]
I've got a one-time warning that licecap is not optimised for macOS.

"Why am I seeing this alert?
Starting with macOS High Sierra 10.13.4, apps that have not been updated to use 64-bit processes produce a one-time alert when opened. This gives users advance notice that they are running 32-bit software, which will not be compatible with macOS in the future."

reference:
https://support.apple.com/en-us/HT208436

**Comment by esaruoho** [comment]
would be great to tackle this for sure!

**Comment by falcondai** [comment]
I see the same warning on my macOS (same version). I wonder how hard it is to solve this issue? Is it just a matter of recompiling with a different flag?

**Comment by ppaulojr** [comment]
https://github.com/justinfrankel/licecap/pull/49

**Comment by esaruoho** [comment]
@ppaulojr and #40 and #46
.. seems like this is a really wanted feature.

**Comment by esaruoho** [comment]
fixed by #49 - once the PR gets merged in by @justinfrankel

**Comment by valentin-nasta** [comment]
Hi @esaruoho, I think this issue can be closed.

**Comment by esaruoho** [comment]
@valentin-nasta  i did not create this issue, so i cannot close it. but, you can close this. can you close it,please? :)

**Comment by esaruoho** [comment]
@valentin-nasta can you close this ticket, please?

**Comment by valentin-nasta** [comment]
@esaruoho thank you for the reminder, I checked it now and it looks good.
