### ISSUE TITLE
Anybody facing it downloading it?

### ISSUE THREAD

**Issue by digitalharesh** [justinfrankel/licecap#53]
I was looking to download [licecap](http://www.fileopt.com/software/licecap)
is there anybody faced issues to download it?

**Comment by digitalharesh** [comment]
ok, finally got it, it was my side to taken care to download [licecap](http://www.fileopt.com/software/licecap) and install it, its all good now.
Thanks

**Comment by esaruoho** [comment]
@digitalharesh if the issue has been fixed, and you no longer have this issue, can you close the ticket, please?
