### ISSUE TITLE
Black screen in Mojave (10.14.1)

### ISSUE THREAD

**Issue by fabersky** [justinfrankel/licecap#58]
When recording on macOS Mojave (10.14.1), the gif appears as black with just the mouse and the elapsed time visible:

<img width="1195" alt="black" src="https://user-images.githubusercontent.com/7327521/49094452-9a0e1400-f266-11e8-99b0-b8988b3946ac.png">

These are my settings, even if i don't think the issue is related to that:

<img width="536" alt="settings" src="https://user-images.githubusercontent.com/7327521/49094494-b316c500-f266-11e8-98ea-23defa8d5427.png">

**Comment by ZxMYS** [comment]
Turned out you need to give it the permission, like this
<img width="660" src="https://user-images.githubusercontent.com/1507278/50670387-168bc500-0f80-11e9-9eaf-96cc929cd1ca.png">

**Comment by fabersky** [comment]
@ZxMYS still the same for me, black screen...

**Comment by esaruoho** [comment]
@fabersky are you using an external screen and recording on that one?

**Comment by esaruoho** [comment]
@fabersky, meet #31 
#31 , meet @fabersky.

**Comment by dialex** [comment]
@esaruoho even without an external monitor, when I switch my virtual desktop I the [recording glitches](https://github.com/justinfrankel/licecap/issues/31#issuecomment-433897573). Should I open a separate issue for it (since it's not related with an external monitor)?

**Comment by NigelThorne** [comment]
You can try running it as Admin. (https://www.nigelthorne.com/2020/07/osx-run-as-admin-context-menu.html) This is how I do it.
