### ISSUE TITLE
Licecap 1.28clang crashes on macOS Mojave 10.14

### ISSUE THREAD

**Issue by esaruoho** [justinfrankel/licecap#61]
Currently if I start up 1.28clang Licecap, and select the filename and start recording, Licecap just vanishes. Is there a newer version that is more compatible with macOS Mojave?

**Comment by AnnDKan** [comment]
Confirming on 10.14.4 Beta (18E184e)

**Comment by sammcj** [comment]
Also getting warnings about it not being optimised - as if it was still 32bit perhaps?

**Comment by esaruoho** [comment]
@sammcj that's a different thing altogether, i believe there's a ticket about it.

but a new build of licecap would be much appreciated, i use licecap daily and now i can't make any .gifs :/

**Comment by stevesparks** [comment]
Following. I am suffering from this issue too.

**Comment by sammcj** [comment]
https://github.com/justinfrankel/licecap/issues/46

**Comment by esaruoho** [comment]
@justinfrankel thanks for posting the experimental 1.29  at your url, i'll close this ticket.
