### ISSUE TITLE
Relationship to https://github.com/lepht/licecap

### ISSUE THREAD

**Issue by jcrben** [justinfrankel/licecap#7]
How does this relate to the other repository https://github.com/lepht/licecap which is a couple hundred commits behind and versioned at 1.25 compared to 1.26 here?

Also `brew cask` is installing with version 1.25 with `url "http://www.cockos.com/licecap/licecap#{version.delete('.')}.dmg"` so it seems to be packaging the older version. This needs a `.dmg` file to be packaged for `brew cask`.

**Comment by valioDOTch** [comment]
Seems as if the other repo got removed; so I guess this issue can be closed.

**Comment by jcrben** [comment]
Thanks, seems to be resolved!
