### ISSUE TITLE
LICEcap could you update for MacOS Catalina 10.15

### ISSUE THREAD

**Issue by sweettimes** [justinfrankel/licecap#71]
I really love LICEcap, it's a super simple and powerful application to screenshot export to GIF file.
And when I updated to MacOS Catalina 10.15 version, it doesn't work with the new OS.
Could you update it, please!

<img width="197" alt="Screen Shot 2019-07-17 at 08 42 21" src="https://user-images.githubusercontent.com/566289/61341228-b8656600-a86f-11e9-8a7c-3c2a5258aeb6.png">
<img width="420" alt="Screen Shot 2019-07-17 at 08 42 29" src="https://user-images.githubusercontent.com/566289/61341234-bbf8ed00-a86f-11e9-8195-badc7846fa59.png">

**Comment by ddriver88** [comment]
I'd like to +1 this. LICEcap was such an integral part of my workflow and it's a bummer that Apple has killed 32bit apps, even though I understand why.

**Comment by grosch** [comment]
The latest version starts up on Catalina but after hitting the Record button and saving the name of the file nothing happens.  It doesn't actually go into record mode.

**Comment by noorulain17** [comment]
The latest `dmg` file for `licecap` from [here](https://www.cockos.com/licecap/licecap129.dmg) works on Mac OS Catalina Beta.

**Comment by admvx** [comment]
I managed to get it working on Catalina, after going through these steps (not sure if all or only some of them are required; maybe try them in reverse order 😅):
- Remove any quarantine flag present on the app's files: open Terminal and run `xattr -d com.apple.quarantine <path_to_licecap>` – e.g. `xattr -d com.apple.quarantine /Applications/LICEcap.app`
- In System Preferences > Security & Privacy > Privacy tab > Full Disk Access sidebar option: unlock the panel and click `+` to add a new entry for the LICEcap application.
- Ensure the saved file includes the `.gif` extension in the name; it doesn't get added automatically and seems to cause the recording to fail otherwise.

**Comment by sweettimes** [comment]
Perfect, It's working now, thank @admvx 
This issue has been solved!

**Comment by abhineshk** [comment]
I noticed that I was able to get it working by following just the last step:
- Ensure the saved file includes the .gif extension in the name; it doesn't get added automatically and seems to cause the recording to fail otherwise.

I got a prompt for giving the app access to recording the screen just after this step. Cheers!

**Comment by kflu** [comment]
> I noticed that I was able to get it working by following just the last step:
> 
> * Ensure the saved file includes the .gif extension in the name; it doesn't get added automatically and seems to cause the recording to fail otherwise.
> 
> I got a prompt for giving the app access to recording the screen just after this step. Cheers!

I can confirm this works  too. Thanks!

**Comment by eliorivero** [comment]
Thanks @admvx! To get it working in Catalina I only needed the first step:

```
xattr -d com.apple.quarantine /Applications/LICEcap.app
```

Thank you!

**Comment by efueger** [comment]
I tried all of the above with no luck. It would never give me the chance to grant it permission. 
- Reinstalling did the trick!!

**Comment by arigoldx** [comment]
I just reinstalled and gave Screen Recording permissions:

<img width="667" alt="Screen Shot 2019-10-23 at 4 01 04 PM" src="https://user-images.githubusercontent.com/1505339/67440500-545ce700-f5ae-11e9-869e-94805dc38041.png">

**Comment by tobecrazy** [comment]
> * LICEca

it works ! thanks!

**Comment by eduardoprentcomau** [comment]
In my case, To get it working in Catalina I performed the uninstall process and deleted the `licecap.ini` file from `Application Support`
~/Library/Application Support/LICEcap/licecap.ini

**Comment by esaruoho** [comment]
hi y'all, where can i find the LICEcap version that supports catalina, please? Is it on homebrew?

**Comment by coltoncook** [comment]
I got it working on Catalina firmware by uninstalling the application from my computer, and then redownloading the application at this address: https://www.cockos.com/licecap/

Hope this helps!

**Comment by gtalarico** [comment]
I tried all of the above, but it would still not work (`xattr`, reintall, full disk access, etc)
After re-reading the thread, I noticed I had missed this step:
>Ensure the saved file includes the .gif extension in the name

After adding `.gif` manually to file name it worked

**Comment by TorvaldsDB** [comment]
I use `Kap` replace it

![image](https://user-images.githubusercontent.com/12232166/74016792-fc67b600-49cd-11ea-9a51-1c799a8b0345.png)

**Comment by joeldenning** [comment]
For me, it didn't work until licecap had both full disk and screen recording permissions. Screen recording permissions could only be given by uninstalling and reinstalling (I must have missed the first initial prompt, and that's the only time you can do it)?

**Comment by JodiWarren** [comment]
> For me, it didn't work until licecap had both full disk and screen recording permissions. Screen recording permissions could only be given by uninstalling and reinstalling (I must have missed the first initial prompt, and that's the only time you can do it)?

For future reference you can add both of those things in System Preferences > Security & Privacy.

On the left, you can choose the Full Disk Access and Screen Recording lists. You can manually add applications to them by unlocking and clicking the little ➕ icon.

**Comment by rcoundon** [comment]
I've discovered that LICECap no longer works after an upgrade to Catalina 10.15.4
I can launch it but after hitting record and selecting a filename nothing happens; the record button is available to press again.
In system preferences I've added full disk access but I'm not able to add applications to the Screen Recording access - i.e. no +/- option - maybe a 10.15.4 thing too

**Comment by joeldenning** [comment]
I also am unable to get Licecap working - after my comment on Feb 14 things stopped working. I have given it full disk access and screen recording access, but it doesn't work for me.

**Comment by gtalarico** [comment]
@joeldenning @rcoundon  did you guys try adding `.gif` to the filename save dialog?

**Comment by joeldenning** [comment]
I've been adding `.gif` all along. But I just tried it again, and was prompted to give Licecap screen recording access again, even though I had already given it access. I clicked on "Open System Preferences" and re-enabled screen recording access, and then it worked!

Am honestly rather confused why I was prompted for screen recording access even though System Preferences already said it had access. I probably got confused somewhere along the way? Now it's working though!

**Comment by rcoundon** [comment]
> @joeldenning @rcoundon did you guys try adding `.gif` to the filename save dialog?

I hadn't tried that and I had the same experience as @joeldenning, I was prompted to grant Screen Record prvileges and then it worked.  Thanks for your help!

**Comment by TorvaldsDB** [comment]
I am back to `LICEcap` again since I found the reason.

You have to rename with extension `.gif` such as `filename.gif`, if you just use the `filename`, you will meet the error hint. 

![image](https://user-images.githubusercontent.com/12232166/79936483-34897b80-848a-11ea-9aa8-7be0528aa551.png)

**Comment by conr** [comment]
I just deleted my old installation of Licecap and installed the latest version. You'll then be prompted to grant some screen recording permissions. Do that and you're Gucci 👌

**Comment by mikelyons** [comment]
My problem was that on first run a dialog popped explaining that LICEcap has been blocked from recording the screen and I missed this poppup, solution pictured above fixed it for me (system preferences, security, privacy, screen recording)

**Comment by kral2** [comment]
> hi y'all, where can i find the LICEcap version that supports catalina, please? Is it on homebrew?

Working with v1.3.0 installed as a homebrew cask
`> brew install licecap`

You have first to give full disk access from "security & privacy" preference menu to have LICEcap also ask for "Screen Recording" permission.
