### ISSUE TITLE
macOS Catalina requires .gif extension to be hand-written, can this be fixed?

### ISSUE THREAD

**Issue by esaruoho** [justinfrankel/licecap#80]
Since I now need to type `.gif` at the end of all files, with macOS Catalina, otherwise the recording does not start.

**Comment by macgyver** [comment]
Aaaaa thanks so much for realizing this workaround existed! I thought recording was 100% busted

**Comment by tychi-nflx** [comment]
Also thanks for this workaround, I've been not using LICEcap for a while now. 🎉

**Comment by m2mathew** [comment]
LIFESAVER. I am passing this on to all of my LICEcap-loving friends immediately.

**Comment by JasonMannon** [comment]
Happy to be using LICEcap again

**Comment by merlos** [comment]
Thanks for the tip! I really like the simplicity of this app.

**Comment by justinfrankel** [comment]
Fixed in 1.30
