### ISSUE TITLE
I can confirm this works too. Thanks!

### ISSUE THREAD

**Issue by essencelite** [justinfrankel/licecap#81]
I noticed that I was able to get it working by following just the last step:
- Ensure the saved file includes the .gif extension in the name; it doesn't get added automatically and seems to cause the recording to fail otherwise.

I got a prompt for giving the app access to recording the screen just after this step. Cheers!

_Originally posted by @abhineshk in https://github.com/justinfrankel/licecap/issues/71#issuecomment-542028032_

**Comment by justinfrankel** [comment]
Fixed in 1.30
